/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ChatForm: typeof import('./src/components/chat/ChatForm.vue')['default']
    component: typeof import('vue')['component']
    ConsDialog: typeof import('./src/components/Dialog/ConsDialog.vue')['default']
    DefaultLayout: typeof import('./src/layouts/defaultLayout.vue')['default']
    DocsDialog: typeof import('./src/components/Dialog/DocsDialog.vue')['default']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    OrderDialog: typeof import('./src/components/Dialog/OrderDialog.vue')['default']
    TimeDialog: typeof import('./src/components/Dialog/TimeDialog.vue')['default']
    TLAuth: typeof import('./src/components/Auth/components/TLAuth.vue')['default']
    TLAuthForm: typeof import('./src/components/Auth/components/TLAuthForm.vue')['default']
    TLBtn: typeof import('./src/components/Btn/components/TLBtn.vue')['default']
    TLCheckbox: typeof import('./src/components/Checkbox/components/TLCheckbox.vue')['default']
    TLFooter: typeof import('./src/components/TLFooter.vue')['default']
    TLFormCodePassed: typeof import('./src/components/Auth/components/TLFormCodePassed.vue')['default']
    TLHeader: typeof import('./src/components/Header/components/TLHeader.vue')['default']
    TLHeaderMenu: typeof import('./src/components/Menu/components/TLHeaderMenu.vue')['default']
    TLInput: typeof import('./src/components/Input/components/TLInput.vue')['default']
    TLLogo: typeof import('./src/components/Logo/components/TLLogo.vue')['default']
    TLMyPackagesItem: typeof import('./src/components/MyPackagesItem/TLMyPackagesItem.vue')['default']
    TLPackageServicesInfo: typeof import('./src/components/PackageServicesInfo/components/TLPackageServicesInfo.vue')['default']
    TLPackageServicesItem: typeof import('./src/components/PackageServicesInfo/components/TLPackageServicesItem.vue')['default']
    TLPayment: typeof import('./src/components/Payment/components/TLPayment.vue')['default']
    TLPaymentBack: typeof import('./src/components/Payment/components/TLPaymentBack.vue')['default']
    TLPaymentInfoForm: typeof import('./src/components/Payment/components/TLPaymentInfoForm.vue')['default']
    TLPhone: typeof import('./src/components/Contact/components/Phone/TLPhone.vue')['default']
    TLProfileForm: typeof import('./src/components/ProfileInfo/components/TLProfileForm.vue')['default']
    TLProfileInfo: typeof import('./src/components/ProfileInfo/components/TLProfileInfo.vue')['default']
    TLRadio: typeof import('./src/components/Radio/components/TLRadio.vue')['default']
    TLRecommendedDoctor: typeof import('./src/components/TLRecommendedDoctor/components/TLRecommendedDoctor.vue')['default']
    TLTitleBg: typeof import('./src/components/TLTitleBg/components/TLTitleBg.vue')['default']
  }
}
