apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.client_site.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.client_site.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Values.chart }}
  annotations:
    rollme: {{ randAlphaNum 5 | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.client_site.name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.client_site.name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      containers:
        - env:
            {{- range $key, $val := .Values.client_site.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
          image: {{ .Values.client_site.image }}
          envFrom:
            - configMapRef:
                name: app-config
          imagePullPolicy: {{ .Values.pullPolicy }}
          name: {{ .Values.client_site.name }}
          ports:
            - containerPort: {{ .Values.client_site.port }}
      restartPolicy: Always
